name: tencent_cos_dart
description: Tencent Cloud COS presigned URL signing for Dart.
version: 0.1.1
repository: https://github.com/Metaildust/gen

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  crypto: ^3.0.7

dev_dependencies:
  test: ^1.25.5
